Código da Equipe: 08
Componentes:
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Maria Eduarda Benfica Gonçalves; maria.g@aln.senaicimatec.edu.br; +55 (71) 98238-8540
	Ricardo Alexandre Santos da Silva; ricardo.silva@aln.senaicimatec.edu.br; +55 (71) 99931-9500

RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: MeuTeste.241
----------------------------------------------------------------------------------------------
Lexeme: programa, Código: A17, Indice na Tab. de Simbolos: None, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: programa1, Código: C06, Indice na Tab. de Simbolos: 1, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: funcoes, Código: A12, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: funcoes1, Código: C05, Indice na Tab. de Simbolos: 2, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: (, Código: B02, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: a, Código: C07, Indice na Tab. de Simbolos: 3, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: ,, Código: B04, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: real, Código: A18, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: b, Código: C07, Indice na Tab. de Simbolos: 4, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: ), Código: B03, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: {, Código: B11, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: real, Código: A18, Indice na Tab. de Simbolos: None, Linha: 3
---------------------------------------------------------------------------------------------
Lexeme: var1, Código: C07, Indice na Tab. de Simbolos: 5, Linha: 3
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 3
---------------------------------------------------------------------------------------------
Lexeme: b, Código: C07, Indice na Tab. de Simbolos: 4, Linha: 3
---------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: var2, Código: C07, Indice na Tab. de Simbolos: 6, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: a, Código: C07, Indice na Tab. de Simbolos: 3, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: real, Código: A18, Indice na Tab. de Simbolos: None, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: var3, Código: C07, Indice na Tab. de Simbolos: 7, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: var1, Código: C07, Indice na Tab. de Simbolos: 5, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: +, Código: B16, Indice na Tab. de Simbolos: None, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: 2.5, Código: C04, Indice na Tab. de Simbolos: 8, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: var4, Código: C07, Indice na Tab. de Simbolos: 9, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: var2, Código: C07, Indice na Tab. de Simbolos: 6, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: *, Código: B14, Indice na Tab. de Simbolos: None, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: 2, Código: C03, Indice na Tab. de Simbolos: 10, Linha: 7
---------------------------------------------------------------------------------------------
Lexeme: retorna, Código: A19, Indice na Tab. de Simbolos: None, Linha: 9
---------------------------------------------------------------------------------------------
Lexeme: var4, Código: C07, Indice na Tab. de Simbolos: 9, Linha: 9
---------------------------------------------------------------------------------------------
Lexeme: }, Código: B12, Indice na Tab. de Simbolos: None, Linha: 10
---------------------------------------------------------------------------------------------
Lexeme: funcoes1, Código: C07, Indice na Tab. de Simbolos: 2, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: (, Código: B02, Indice na Tab. de Simbolos: None, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: 20, Código: C03, Indice na Tab. de Simbolos: 11, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: ,, Código: B04, Indice na Tab. de Simbolos: None, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: 2.5, Código: C04, Indice na Tab. de Simbolos: 8, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: ), Código: B03, Indice na Tab. de Simbolos: None, Linha: 12
---------------------------------------------------------------------------------------------
Lexeme: var2, Código: C07, Indice na Tab. de Simbolos: 6, Linha: 14
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 14
---------------------------------------------------------------------------------------------
Lexeme: 10, Código: C03, Indice na Tab. de Simbolos: 12, Linha: 14
---------------------------------------------------------------------------------------------
Lexeme: cadeia, Código: A01, Indice na Tab. de Simbolos: None, Linha: 15
---------------------------------------------------------------------------------------------
Lexeme: ola, Código: C07, Indice na Tab. de Simbolos: 13, Linha: 15
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 15
---------------------------------------------------------------------------------------------
Lexeme: "ola", Código: C01, Indice na Tab. de Simbolos: 14, Linha: 15
---------------------------------------------------------------------------------------------
Lexeme: cadeia, Código: A01, Indice na Tab. de Simbolos: None, Linha: 16
---------------------------------------------------------------------------------------------
Lexeme: text2, Código: C07, Indice na Tab. de Simbolos: 15, Linha: 16
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 16
---------------------------------------------------------------------------------------------
Lexeme: "qwertyuiopasd_fghjklzxcvbnmqw, Código: C01, Indice na Tab. de Simbolos: 16, Linha: 16
---------------------------------------------------------------------------------------------