Código da Equipe: 08
Componentes:
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660

RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: MeuTeste.241
----------------------------------------------------------------------------------------------
Átomo: programa, Código: A17, Lexeme: programa, Indice na Tab. de Simbolos: None, Linha: [1]
---------------------------------------------------------------------------------------------
Átomo: nomPrograma, Código: C06, Lexeme: programa1, Indice na Tab. de Simbolos: 1, Linha: [1]
---------------------------------------------------------------------------------------------
Átomo: funcoes, Código: A12, Lexeme: funcoes, Indice na Tab. de Simbolos: None, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: funcoes1, Indice na Tab. de Simbolos: 2, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: (, Código: B02, Lexeme: (, Indice na Tab. de Simbolos: None, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: ), Código: B03, Lexeme: ), Indice na Tab. de Simbolos: None, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: {, Código: B11, Lexeme: {, Indice na Tab. de Simbolos: None, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: }, Código: B12, Lexeme: }, Indice na Tab. de Simbolos: None, Linha: [4]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var1, Indice na Tab. de Simbolos: 3, Linha: [5]
---------------------------------------------------------------------------------------------
Átomo: :=, Código: B06, Lexeme: :=, Indice na Tab. de Simbolos: None, Linha: [5]
---------------------------------------------------------------------------------------------
Átomo: consReal, Código: C04, Lexeme: 1.5, Indice na Tab. de Simbolos: 4, Linha: [5]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var2, Indice na Tab. de Simbolos: 5, Linha: [6]
---------------------------------------------------------------------------------------------
Átomo: :=, Código: B06, Lexeme: :=, Indice na Tab. de Simbolos: None, Linha: [6]
---------------------------------------------------------------------------------------------
Átomo: consInteiro, Código: C03, Lexeme: 20, Indice na Tab. de Simbolos: 6, Linha: [6]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var3, Indice na Tab. de Simbolos: 7, Linha: [8]
---------------------------------------------------------------------------------------------
Átomo: :=, Código: B06, Lexeme: :=, Indice na Tab. de Simbolos: None, Linha: [8]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var1, Indice na Tab. de Simbolos: 3, Linha: [8]
---------------------------------------------------------------------------------------------
Átomo: +, Código: B16, Lexeme: +, Indice na Tab. de Simbolos: None, Linha: [8]
---------------------------------------------------------------------------------------------
Átomo: consReal, Código: C04, Lexeme: 2.5, Indice na Tab. de Simbolos: 8, Linha: [8]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var4, Indice na Tab. de Simbolos: 9, Linha: [9]
---------------------------------------------------------------------------------------------
Átomo: :=, Código: B06, Lexeme: :=, Indice na Tab. de Simbolos: None, Linha: [9]
---------------------------------------------------------------------------------------------
Átomo: variavel, Código: C07, Lexeme: var2, Indice na Tab. de Simbolos: 5, Linha: [9]
---------------------------------------------------------------------------------------------
Átomo: *, Código: B14, Lexeme: *, Indice na Tab. de Simbolos: None, Linha: [9]
---------------------------------------------------------------------------------------------
Átomo: consInteiro, Código: C03, Lexeme: 2, Indice na Tab. de Simbolos: 10, Linha: [9]
---------------------------------------------------------------------------------------------