Código da Equipe: 08
Componentes:
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660

RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: MeuTeste.241
----------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var1, Indice na Tab. de Simbolos: 1, Linha: [1]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var2, Indice na Tab. de Simbolos: 2, Linha: [1]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var3, Indice na Tab. de Simbolos: 3, Linha: [1]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var1, Indice na Tab. de Simbolos: 1, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var1, Indice na Tab. de Simbolos: 1, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var1, Indice na Tab. de Simbolos: 1, Linha: [2]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var2, Indice na Tab. de Simbolos: 2, Linha: [3]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var2, Indice na Tab. de Simbolos: 2, Linha: [3]
---------------------------------------------------------------------------------------------
Átomo: nomFuncao, Código: C05, Lexeme: var1, Indice na Tab. de Simbolos: 1, Linha: [3]
---------------------------------------------------------------------------------------------