Código da Equipe: 08
Componentes:
	Gabriel de Araujo Santos Rocha; gabriel.rocha@aln.senaicimatec.edu.br; +55 (71) 98526-8660
	Maria Eduarda Benfica Gonçalves; maria.g@aln.senaicimatec.edu.br; +55 (71) 98238-8540
	Ricardo Alexandre Santos da Silva; ricardo.silva@aln.senaicimatec.edu.br; +55 (71) 99931-9500

RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: MeuTeste.241
----------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: var1, Código: C07, Indice na Tab. de Simbolos: 1, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: 10, Código: C03, Indice na Tab. de Simbolos: 2, Linha: 1
---------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: var2, Código: C07, Indice na Tab. de Simbolos: 3, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: 20, Código: C03, Indice na Tab. de Simbolos: 4, Linha: 2
---------------------------------------------------------------------------------------------
Lexeme: inteiro, Código: A14, Indice na Tab. de Simbolos: None, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: var3, Código: C07, Indice na Tab. de Simbolos: 5, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: :=, Código: B06, Indice na Tab. de Simbolos: None, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: var1, Código: C07, Indice na Tab. de Simbolos: 1, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: +, Código: B16, Indice na Tab. de Simbolos: None, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: var2, Código: C07, Indice na Tab. de Simbolos: 3, Linha: 4
---------------------------------------------------------------------------------------------
Lexeme: imprime, Código: A13, Indice na Tab. de Simbolos: None, Linha: 6
---------------------------------------------------------------------------------------------
Lexeme: var3, Código: C07, Indice na Tab. de Simbolos: 5, Linha: 6
---------------------------------------------------------------------------------------------